version: "3.9"
services:
  web:
    volumes:
      - vscode-extensions:/root/.vscode-server/extensions
      - vscode-extensions-insiders:/root/.vscode-server-insiders/extensions
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  vscode-extensions:
  vscode-extensions-insiders:
