name: "publish web through node:17-slim"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    container: 
      image: node:17-slim
    steps:
      - name: Checkout Hooks
        uses: actions/checkout@v2 
        with:
          repository: utkusarioglu/hooks
          path: hooks
      - name: Checkout Web
        uses: actions/checkout@v2
        with:
          repository: utkusarioglu/web
          path: web
      - name: Install hooks dependencies
        working-directory: hooks
        run: yarn install --frozen-lockfile
      - name: Build web
        working-directory: web
        run: |
          yarn install --frozen-lockfile
          yarn ci
      # - name: Cache Web build
      #   uses: actions/cache@v2
      #   env:
      #     cache-name: utkusarioglu-web-build-cache
      #   with:
      #     # npm cache files are stored in `~/.npm` on Linux/macOS
      #     path: web/build
      #     key: utkusarioglu-web-build-cache
      #     # key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      #     # restore-keys: |
      #     #   ${{ runner.os }}-build-${{ env.cache-name }}-
      #     #   ${{ runner.os }}-build-
      #     #   ${{ runner.os }}-
      - name: Builds as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: utkusarioglu-web-build
          path: web/build
